<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-A38V3DO6" failures="2" tests="4" name="runner.TestRunner" time="28.348" errors="0" timestamp="2023-07-17T18:57:06 IST" skipped="0">
  <testcase classname="runner.TestRunner" name="runScenario" time="4.198"/>
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="12.372">
    <failure message="expected [Helloo] but found [Hello]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Helloo] but found [Hello]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at pagess.homePage.checkHelloTxt(homePage.java:40)
at stepDefinitions.checkHomePage_stepDefs.the_user_validate_page_hello(checkHomePage_stepDefs.java:36)
at ✽.The user validate page hello(file:///C:/Users/Sanjay%20Prasad/eclipse-workspace/allurecucumberProject2/src/test/resources/features/checkHomePage.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="7.825">
    <failure message="Failed due to unccessful Logged in message " type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failed due to unccessful Logged in message 
at org.testng.Assert.fail(Assert.java:110)
at stepDefinitions.login_stepDeff.user_is_navigated_to_home_page(login_stepDeff.java:78)
at ✽.User is navigated to home page(file:///C:/Users/Sanjay%20Prasad/eclipse-workspace/allurecucumberProject2/src/test/resources/features/loginPage.feature:10)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.TestRunner" name="runScenario" time="3.953"/>
  <system-out/>
</testsuite> <!-- runner.TestRunner -->
